version: "3.8"

# --- THE FORM ---
x-nodel-config:
  url: bamboo.donahuenet.xyz
  port: 3000
  group: Services
  icon: bambu.png
# ----------------

services:
  bambustudio:
    image: lscr.io/linuxserver/bambustudio:latest
    container_name: bambustudio
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DARK_MODE=true #optional
    volumes:
      - /path/to/bambustudio/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped