version: '3.3'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      ENABLE_RAG_WEB_SEARCH: 'True'
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: '10'
      RAG_WEB_SEARCH_ENGINE: '"searxng"'
      RAG_WEB_SEARCH_RESULT_COUNT: '3'
      SEARXNG_QUERY_URL: '"https://searx.donahuenet.xyz/search?q="'
    volumes:
     - /mnt/shared/swarm/webui:/app/backend/data
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.webui.service: webui-svc
        homepage.group: Services
        traefik.http.middlewares.webui-inflight.inflightreq.amount: '50'
        traefik.http.middlewares.webui-ratelimit.ratelimit.average: '100'
        homepage.href: https://donai.donahuenet.xyz
        homepage.icon: open-webui.png
        traefik.http.routers.webui.middlewares: webui-ratelimit,webui-inflight
        homepage.name: Open WebUI
        traefik.http.services.webui-svc.loadbalancer.server.port: '8080'
        homepage.siteMonitor: http://open-webui:8080
        homepage.description: AI Chat Interface
        traefik.http.middlewares.webui-ratelimit.ratelimit.burst: '50'
        traefik.enable: 'true'
        traefik.http.routers.webui.rule: Host(`donai.donahuenet.xyz`)
        traefik.http.routers.webui.tls: 'true'
        traefik.http.routers.webui.entrypoints: websecure
      restart_policy:
        condition: on-failure
networks:
  traefik-public:
    external: true
